### ISSUE TITLE
state place tract with return_geometry argument doesn't work

### ISSUE THREAD

**Issue by kevalshah90** [datamade/census_area#11]
I am trying to use the example from README. 

`old_homes_geojson = c.acs5.state_place_tract(('NAME', 'B25034_010E'), 17, 14000),  return_geometry=True)
 `
The code is missing a parenthesis. What is the correct format to get tract level geometries? 

I am trying to get all the median household income in all census tracts in a county with their geometries. 

```
c.acs5.state_county_tract('NAME', 
                          states.CA.fips, 
                          '075', 
                          Census.ALL,
                          return_geometry=True)
```

**Comment by hancush** [comment]
Hi, @kevalshah90 – Thanks for pointing out our typo! I've updated the code examples in the new documentation, available here: https://census-area.readthedocs.io/en/latest/

Note that the `state_county_tract` method comes from our upstream `census` library and does not have the `return_geometry` option. 

`census_area` is currently limited to incorporated places and user-provided geometries. To get values and shapes for all tracts in a county, you could pass the county shape to `census_area`'s `geo_tract` method, then iterate over the output to create a GeoJSON object yourself. More on `geo_tract`: https://census-area.readthedocs.io/en/latest/#census_area.core.ACS5Client.geo_tract
