### ISSUE TITLE
Unable to reproduce example in README

### ISSUE THREAD

**Issue by mariellep** [datamade/census_area#12]
Since I'm new to these, I figured I'd start out by trying to reproduce the existing examples:
`c = Census(api_key)`
`c.acs5.state_place_tract(('NAME', 'B25034_010E'), 17, 14000) `

This raises a TypeError with the following message: " '<' not supported between instances of 'NoneType' and 'NoneType' "

I've been able to access other objects such as c.acs5.years, but the documentation isn't complete enough for me to troubleshoot this. Any help much appreciated!

![image](https://user-images.githubusercontent.com/3780369/157751118-ce0f7757-0773-4a20-b3fd-edd0c0cefbb5.png)

**Comment by hancush** [comment]
@mariellep Just pushed a new release to PyPI addressing this error. Want to give the example code another go?

**Comment by mariellep** [comment]
@hancush It's not raising the TypeError any more, but it was hanging for ~6.5 minutes before I finally killed it. What's the amount of time it should be taking for `c.acs5.state_place_tract(('NAME', 'B25034_010E'), 17, 14000) ` ?

**Comment by hancush** [comment]
@mariellep Ah, yes, it takes a bit to run because there are 800+ tracts to query in Chicago. 😬 I'd love to look at whether we can improve performance using bulk queries, and barring that, to add some indicator of progress.

It just finished in ~10 min on my machine. Would you mind giving it a bit longer to work?

**Comment by mariellep** [comment]
@hancush Yup, it worked! The optimization would obviously be nice but that's an enhancement. I think we can call this specific issue fixed.
