### ISSUE TITLE
Cannot import census_area library

### ISSUE THREAD

**Issue by vaibhavbafna5** [datamade/census_area#8]
attempted this:

`from census_area import Census

api_key = "key"
c = Census(api_key)`

received this as an error:

`Traceback (most recent call last):
  File "exploration.py", line 1, in <module>
    from census_area import Census
  File "/opt/anaconda3/lib/python3.7/site-packages/census_area/__init__.py", line 205, in <module>
    class SF3Client(census.core.SF3Client, GeoClient):
AttributeError: module 'census.core' has no attribute 'SF3Client'`

Was able to temporarily resolve this by just commenting out usage of SF3Client, but this doesn't seem like a long-term solution especially if I deploy my application to some place like Heroku/AWS/GCP.

**Comment by hancush** [comment]
@vaibhavbafna5 This should be resolved in the latest release, 0.4.0.
